# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5addf81703bb6de80ec1b2f4a700eea6f9ed355cefd82ec79d74edfd5bf13a29f1d3db72fa868e383b9975b2ef36dcc326291674ba63ea851e50d6d9db96a28

test:
  secret_key_base: 1d8258ce33336f0cedfcea6ec259ef90167fc6ee7ce1a9f33f3265998aec952ed3dfbbef5557fcc9d3a491be769ff25fbc2f445c339488a60054d8c247e82ebd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
